Repository javibu13/sanvalero-2dam-firsteval, pull requests merged in 2025-01, with the labels that each got.

#1 First version of JavaFX application with basic logic with free test api connection
  javaFX/pom.xml
  javaFX/src/main/java/com/svalero/javaFX/MainApp.java
  javaFX/src/main/java/com/svalero/javaFX/controller/MainController.java
  javaFX/src/main/java/com/svalero/javaFX/service/ApiService.java
  javaFX/src/main/resources/com/svalero/javaFX/view/main-view.fxml
Labels: good first issue

#2 First api version
  .gitignore
  api/apiFilm.yaml
  api/pom.xml
  api/src/main/java/com/svalero/films/FilmsApplication.java
  api/src/main/java/com/svalero/films/config/SecurityConfig.java
  api/src/main/java/com/svalero/films/controller/AuthController.java
  api/src/main/java/com/svalero/films/controller/DirectorController.java
  api/src/main/java/com/svalero/films/controller/FilmController.java
  api/src/main/java/com/svalero/films/domain/Director.java
  api/src/main/java/com/svalero/films/domain/Film.java
  api/src/main/java/com/svalero/films/exception/ErrorResponse.java
  api/src/main/java/com/svalero/films/exception/GlobalExceptions.java
  api/src/main/java/com/svalero/films/exception/InvalidDataException.java
  api/src/main/java/com/svalero/films/exception/ResourceNotFoundException.java
  api/src/main/java/com/svalero/films/repository/DirectorRepository.java
  api/src/main/java/com/svalero/films/repository/FilmRepository.java
  api/src/main/java/com/svalero/films/security/JwtAuthenticationFilter.java
  api/src/main/java/com/svalero/films/security/JwtTokenService.java
  api/src/main/java/com/svalero/films/service/DirectorService.java
  api/src/main/java/com/svalero/films/service/FilmService.java
  api/src/main/resources/logback.xml
  api/src/test/java/com/svalero/films/FilmsApplicationTests.java
  devops/dbCreation.sql
Labels: good first issue

#3 Add basic web files to use for the PHP web application
  web/directors.php
  web/films.php
  web/images/director_button.png
  web/images/director_placeholder.png
  web/images/film_button.png
  web/images/film_placeholder.png
  web/include/footer.php
  web/include/head.php
  web/include/header.php
  web/index.php
  web/styles.css
Labels: good first issue

#5 Fix some response code status like they appear in the OpenAPI document
  api/src/main/java/com/svalero/films/service/DirectorService.java
  api/src/main/java/com/svalero/films/service/FilmService.java
Labels: bug, documentation

#6 Fix fetch data retrieve and set CORS configuration
  web/directors.php
  web/films.php
  web/include/cors.php
  web/include/head.php
Labels: bug, enhancement

#7 Add allow CORS configuration and update README.md with application.pr…
  README.md
  api/src/main/java/com/svalero/films/config/CorsConfig.java
Labels: documentation, enhancement

#8 Modifiy exceptionHandlers, add Patch Operation, and complete the OpenApi.
  api/apiFilm.yaml
  api/src/main/java/com/svalero/films/controller/DirectorController.java
  api/src/main/java/com/svalero/films/controller/FilmController.java
  api/src/main/java/com/svalero/films/service/DirectorService.java
  api/src/main/java/com/svalero/films/service/FilmService.java
Labels: bug, documentation

#9 First project version with mandatory requirements
  .gitignore
  README.md
  api/apiFilm.yaml
  api/pom.xml
  api/src/main/java/com/svalero/films/FilmsApplication.java
  api/src/main/java/com/svalero/films/config/CorsConfig.java
  api/src/main/java/com/svalero/films/config/SecurityConfig.java
  api/src/main/java/com/svalero/films/controller/AuthController.java
  api/src/main/java/com/svalero/films/controller/DirectorController.java
  api/src/main/java/com/svalero/films/controller/FilmController.java
  api/src/main/java/com/svalero/films/domain/Director.java
  api/src/main/java/com/svalero/films/domain/Film.java
  api/src/main/java/com/svalero/films/exception/ErrorResponse.java
  api/src/main/java/com/svalero/films/exception/GlobalExceptions.java
  api/src/main/java/com/svalero/films/exception/InvalidDataException.java
  api/src/main/java/com/svalero/films/exception/ResourceNotFoundException.java
  api/src/main/java/com/svalero/films/repository/DirectorRepository.java
  api/src/main/java/com/svalero/films/repository/FilmRepository.java
  api/src/main/java/com/svalero/films/security/JwtAuthenticationFilter.java
  api/src/main/java/com/svalero/films/security/JwtTokenService.java
  api/src/main/java/com/svalero/films/service/DirectorService.java
  api/src/main/java/com/svalero/films/service/FilmService.java
  api/src/main/resources/logback.xml
  api/src/test/java/com/svalero/films/FilmsApplicationTests.java
  devops/dbCreation.sql
  devops/docker-compose.yml
  javaFX/pom.xml
  javaFX/src/main/java/com/svalero/javaFX/MainApp.java
  javaFX/src/main/java/com/svalero/javaFX/controller/MainController.java
  javaFX/src/main/java/com/svalero/javaFX/service/ApiService.java
  javaFX/src/main/resources/com/svalero/javaFX/view/main-view.fxml
  web/directors.php
  web/films.php
  web/images/director_button.png
  web/images/director_placeholder.png
  web/images/film_button.png
  web/images/film_placeholder.png
  web/include/cors.php
  web/include/footer.php
  web/include/head.php
  web/include/header.php
  web/index.php
  web/styles.css
Labels: enhancement
