Repository javibu13/sanvalero-2dam-firsteval, pull requests merged in 2025-02, with the labels that each got.

#10 Fix cors include to be in the first line of each main PHP file instad of inside other include
  web/directors.php
  web/films.php
  web/include/head.php
  web/index.php
Labels: bug

#11 Add films and directors creation in web app.
  web/create_director.php
  web/create_film.php
  web/index.php
  web/styles.css
Labels: enhancement

#13 Add styles.css and modifed styles
  javaFX/src/main/java/com/svalero/javaFX/controller/MainController.java
  javaFX/src/main/resources/com/svalero/javaFX/view/main-view.fxml
  javaFX/src/main/resources/styles.css
Labels: enhancement

#14 Add DELETE films and directors
  web/directors.php
  web/films.php
  web/include/head.php
  web/index.php
  web/styles.css
Labels: enhancement

#15 Add docker configuration to deploy
  devops/Dockerfile.api
  devops/Dockerfile.web
  devops/docker-compose.yml
Labels: enhancement

#17 Final Project
  README.md
  javaFX/src/main/java/com/svalero/javaFX/MainApp.java
Labels: documentation

#18 Add Filter director by genre and all films by director
  api/apiFilm.yaml
  api/src/main/java/com/svalero/films/controller/DirectorController.java
  api/src/main/java/com/svalero/films/controller/FilmController.java
  api/src/main/java/com/svalero/films/repository/DirectorRepository.java
  api/src/main/java/com/svalero/films/repository/FilmRepository.java
  api/src/main/java/com/svalero/films/service/DirectorService.java
Labels: enhancement

#19 Final project
  api/apiFilm.yaml
  api/src/main/java/com/svalero/films/controller/DirectorController.java
  api/src/main/java/com/svalero/films/controller/FilmController.java
  api/src/main/java/com/svalero/films/repository/DirectorRepository.java
  api/src/main/java/com/svalero/films/repository/FilmRepository.java
  api/src/main/java/com/svalero/films/service/DirectorService.java
Labels: documentation, enhancement

#20 Create Requirements.md
  Requirements.md
Labels: documentation
